name: sw

on:
  push:
  pull_request:
  schedule:
    # every day
    - cron: 0 0 * * *

jobs:
  windows:
    runs-on: windows-2022    
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - run: ./sw build

  linux:
    runs-on: ubuntu-22.04
    container: fedora:latest
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo dnf -y update
        sudo dnf -y install flex bison cmake which gcc clang clang-tools-extra lld git \
          mesa-libGL-devel mesa-libEGL-devel
    - uses: egorpugin/sw-action@master
    - run: ./sw build -compiler gcc

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - name: install
      run: brew install flex bison gcc llvm
    #- run: sudo xcode-select --switch /Library/Developer/CommandLineTools
    - name: build
      run: |
        export PATH="/usr/local/opt/flex/bin:$PATH"
        export PATH="/usr/local/opt/bison/bin:$PATH"
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        export PATH="/usr/local/opt/llvm/bin:$PATH"
        export PATH="/opt/homebrew/Cellar/llvm/bin:$PATH"
        export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
        ./sw build -compiler clang-18
        # /opt/homebrew/opt/gcc/bin for macos-14
        #-platform x64
        
