name: sw

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022    
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - run: ./sw build
      
  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - name: install
      run: brew install flex bison gcc
    - name: build
      run: |
        export PATH="/usr/local/opt/flex/bin:$PATH"
        export PATH="/usr/local/opt/bison/bin:$PATH"
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        ./sw build -compiler gcc-11

  linux:
    runs-on: ubuntu-22.04
    container: fedora:36
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo dnf -y update
        sudo dnf -y install flex bison cmake which gcc clang clang-tools-extra lld git \
          mesa-libGL-devel mesa-libEGL-devel
    - uses: egorpugin/sw-action@master
    - run: ./sw build -compiler gcc
